// Regenerates site/assets/js/config.js from environment variables.
//
// Used by the Docker build (see Dockerfile) so a container can be pointed at
// any Supabase project without editing source. Reads SUPABASE_URL / SUPABASE_KEY
// (or the VITE_* names), falling back to the public demo project. The generated
// file still honours a runtime `window.__ENSINOLIBRE__` override.
//
// NOT part of the normal npm/dev flow — it overwrites the committed, hand-
// documented config.js, which stays the source of truth for local development.
import { writeFileSync } from 'node:fs';

const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL
  || 'https://edgdxuvzyhwqidjjbidq.supabase.co';
const key = process.env.SUPABASE_KEY || process.env.VITE_SUPABASE_ANON_KEY
  || 'sb_publishable_E1qrfBQlbs6BVRksbX6zbQ_hc_63063';

const out = `/* Generated by scripts/gen-config.mjs from SUPABASE_URL/SUPABASE_KEY.
 * Do not edit in a container build; edit the committed config.js for local dev. */
const cfg = (typeof window !== 'undefined' && window.__ENSINOLIBRE__) || {};
export const SUPABASE_URL = cfg.SUPABASE_URL || ${JSON.stringify(url)};
export const SUPABASE_KEY = cfg.SUPABASE_KEY || ${JSON.stringify(key)};
`;

const target = new URL('../site/assets/js/config.js', import.meta.url);
writeFileSync(target, out);
console.log(`gen-config: wrote ${target.pathname} (url=${url})`);
